### PR TITLE
Mark api response as 'static

### PR DESCRIPTION
**Pull request by kpcyrd**
Since the returned struct outlives the buffer that's used to read the http response I think the response is always a 'static Cow::Owned, so marking it 'static would allow passing it between threads. If possible I'd recommend changing it from `Cow<str>` to just `String` though since it would make the library easier to use and allow things like `Arc<Mutex<Vec<UserRepresentation>>>`.

### CODE REVIEW

**Comment by kilork** [comment]
Yes, I also thought it could be a complication without real reason to do this. My problem, that I do not have a more complicated use case, just a trivial command line utility. I would switch to String with next `keycloak` version.

Do you think this is 12.0.1 or 12.1.0? If someone has a structure, which refers our structure would it be still backward compatible? I know I have probably 2-3 users of this crate, but still do not want to damage someone accidently.

**Comment by kpcyrd** [comment]
Awesome! Do you want me to submit a PR for that or do you want to do this yourself? I'd rather go with that solution instead of this PR. The change to String requires a 13.0.0 release. Thanks!

**Comment by kilork** [comment]
I will just do a quick check tomorrow for a backward compatibility. Yes, we need new keycloak version for smooth String switch. This version 12 was not the best experience, because they lost type info in documentation, hopefully version 13 would be somehow better. I have no issue to do it by myself, but if you really want to do this - you are always welcome. In any case thank you for your contribution!

**Comment by kilork** [comment]
I found more place to replace with static, seem like it is ok now.

**Pull request merged**
