### PR TITLE
Facilitate Service Account based admin access with KeycloakServiceAccountAdminToken

### LINKED ISSUE #28: Acquire KeycloakAdminToken via service account
It seems the library is lacking getting an admin token via a [service account](https://www.keycloak.org/docs/latest/server_development/#authenticate-with-a-service-account).

In my local checkout I've demonstrated that this works:

```
    pub async fn acquire_service(
        url: &str,
        client_id: &str,
        client_secret: &str,
        client: &reqwest::Client,
    ) -> Result<KeycloakAdminToken, KeycloakError> {
        let response = client
            .post(&format!(
                "{}/auth/realms/master/protocol/openid-connect/token",
                url,
            ))
            .form(&json!({
                "client_id": client_id,
                "client_secret": client_secret,
                "grant_type": "client_credentials"
            }))
            .send()
            .await?;
        Ok(error_check(response).await?.json().await?)
    }
```

I'd be happy to open up a PR to contribute it back up this weekend, just wondering if you'd have any pre-emptive suggestions or requests so I can make the PR as ready as possible out the gate.

From what I can tell the docs seemed to be wrong in the requirement of these:
> - client_id has a custom "Audience" mapper
> - Included Client Audience: security-admin-console

But I would mention the other requirements in the Doc comments

### PR DESCRIPTION
**Pull request by criminosis**
Closes #28

It didn't seem like there was any automated testing for me to build on, but I've confirmed it at least has worked in the application I'm currently working on fwiw.

### CODE REVIEW

**Comment by criminosis** [comment]
@kilork whenever you have some time 👍

**Comment by criminosis** [comment]
@kilork realized I overlooked handling the long life of an application using admin service account. Refactored to just getting an admin token each call to the Admin API for now. But left some comments for future improvement by inspecting the token, etc. To go that far though would require some kind of jwt deserialization library in order to read the `exp` field in the token and I didn't want to assume this PR would be justified in adding an additional dependency at this time.

**Comment by criminosis** [comment]
@kilork I think `KeycloakAdmin::new` was unintentionally constrained to a certain struct instead of token supplier like I _think_ was intended. But it'd be worth a closer look by you for confirmation in https://github.com/kilork/keycloak/pull/30/commits/0c73e86dffa6d11da631bf80ff2fc60d251af433

**Comment by kilork** [comment]
Hi, I think your code looks legit. Just to know - you need to change generator and then generate `rest.rs`.

**Comment by criminosis** [comment]
@kilork updated the `gen` file and running these commands:

```
cargo run --example gen -- types > src/types2.rs
cargo run --example gen -- rest > src/rest/rest2.rs
mv src/types2.rs src/types.rs
mv src/rest/rest2.rs src/rest/rest.rs
cargo fmt
cargo build
```

produced a successful build and no differences in the output after commit https://github.com/kilork/keycloak/pull/30/commits/5a2f404df228cba31f76e6f7ff7f1e69e369f491

As a side note I ended up having to do the gen commands inside of the WSL instead of Windows directly. I didn't investigate it but something wasn't happy with the output. Cargo kept erroring out saying that `types.rs` was not valid UTF-8 after I regenerated it. Skimming through the code nothing obvious jumped out to me, there wasn't any hard coded linux line endings, etc. But figured it was worth mentioning 🤷‍♂️

**Comment by kilork** [comment]
Thanks for the info. Yeap, I have no real desire to make this `gen.rs` cross platform, but it should not be complicated. I actually have Windows machine, but was always using WSL.

Creating an issue: https://github.com/kilork/keycloak/issues/31

**Pull request merged**
