### PR TITLE
Derive some more traits for the public api

### LINKED ISSUE #105: Derive `Clone` for all public structs
It's better that public api structs derive `Clone`. (For example, `KeycloakAdminToken` doesn't have `Clone`)

And if possible/needed/makes-sense, also `Copy`, `Default`, `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Hash` and `Display`.

### PR DESCRIPTION
**Pull request by omid**
Fixes #105

### CODE REVIEW

**Comment by kilork** [comment]
Hey, thank you for this contribution. Consider we do not write types by hand, they are generated in `openapi.rs`. Please, feel free to adjust integration tests to test extra feature variants. Most important here is `rc` feature.

**Comment by omid** [comment]
Thanks. What is `openapi.rs`?
The one in the examples directory? 🤔🤔

**Comment by kilork** [comment]
Yes, one in examples `directory`.

**Comment by omid** [comment]
So openapi.rs in the examples folder is responsible to generate other files? I'm confused a bit, sorry
If so, why is it in examples of it's not an example?

**Comment by omid** [comment]
I read the code more carefully, after these two PRs, I'll try to restructure the code a bit and move it out of examples dir.

**Pull request merged**
