### PR TITLE
wip: adjust gen.rs to consume Keycloak v23 documentation

### LINKED ISSUE #68: compatibility to keycloak 23 (subGroups, subGroupCount, groups/{id}/children API)
Hi there, thank you a lot for this crate. It seems there are major changes in keycloak 23 that require to change f.e. `GroupRepresentation` as well as add new endpoints. Essentially running crate v21 against a 23 keycloak currently breaks in an unfixable way without this crate adapting new endpoints and struct changes:

One of the behaviors of 23 is, that the groups api does not return subGroups anymore, just a Count, and requires a new endpoint to fetch children of a group:
https://www.keycloak.org/docs/23.0.0/upgrading/#grouprepresentation-changes

The new API in question would be:
GET /admin/realms/{realm}/groups/{id}/children - Return a paginated list of subgroups that have a parent group corresponding to the group on the URL

I've noticed this repo contains an `update.sh` but I wasn't sure what kind of post-run tasks or checks need to be performed.

The following API docs are relevant (at least for the change I've noticed):
https://www.keycloak.org/docs-api/23.0.1/rest-api/index.html#GroupRepresentation
https://www.keycloak.org/docs-api/23.0.1/rest-api/index.html#_get_adminrealmsrealmgroups
https://www.keycloak.org/docs-api/23.0.1/rest-api/index.html#_get_adminrealmsrealmgroupsidchildren

### PR DESCRIPTION
**Pull request by anthraxx**
Fixes #68

### CODE REVIEW

**Comment by anthraxx** [comment]
For now I did basic adjustments of the gen.rs tooling to consume v23. It properly understands the new structure for return values as well as parameters.
What is still WIP is the mapping of the return types, would be nice if you can help out here @kilork
If you look at the diff i've added some of the type declarations but there is a lot more I wasn't yet sure how to map them.

**Comment by rblaine95** [comment]
> I also still wonder, why they cannot provide simple swagger like API description, which would be more easy to consume. 

https://github.com/keycloak/keycloak/pull/22940 adds the OpenAPI yaml/json, it sounds like they're going to add it with the release of 24.

I've got a copy of the Keycloak 23 OpenAPI yaml/json specs [here](https://github.com/rblaine95/keycloak-openapi/tree/tweaks/OpenApiDefinitions)

**Comment by kilork** [comment]
@rblaine95 this is definitely a much better way to go. This json/yamls still raise some questions about types, but it is still way more better than parsing html. Let us rewrite this to use json or yaml instead.

**Comment by gabrik** [comment]
Hi, I'm interested in the support for the V23, there is any way I can test/help?

**Comment by kilork** [comment]
Closed by #80

**Pull request closed without merging**
